### ISSUE TITLE
Suggestion: Data consistency across multiple related rows

### ISSUE THREAD

**Issue by sburkett** [y-ui/laravel-data-masking#2]
This looks really cool, thanks for putting it together!

One thing that would be awesome is if, based on some criteria, multiple rows could be changed with the same value. This is a silly example, but let's say you have a table/model that is used to store books with author's names. So you might want all rows containing "Tom Clancy" as the author to be replaced with the same value.

Not a very realistic example, but it illustrates the point I hope.  Thanks again!

**Comment by y-ui** [comment]
Thanks for your suggestions!

Now you can update this package and set `'author' => 'text:Tom Clancy'`, then run the command
 `php artisan data:mask --where="author like '%Tom Clancy%'"`

**Comment by sburkett** [comment]
Awesome! I'll give it a look and see how it works. Thanks for the great response time!
