### ISSUE TITLE
数据脱敏处理后，如果需要查看脱敏前的数据怎么办呢？

### ISSUE THREAD

**Issue by mouyong** [y-ui/laravel-data-masking#3]

**Comment by y-ui** [comment]
脱敏后原数据就丢失了，如果需要看脱敏前的数据需要自己备份一下

**Comment by mouyong** [comment]
那是否可以做到脱敏储存与展示，需要的时候查看呢？

储存使用盐值加密即可。然后可逆向。只要项目人员保证盐值的安全就不会存在信息泄漏的问题。

如果泄漏了，可以更新加密信息，重新生成加密数据。

**Comment by y-ui** [comment]
好想法，但是这不是脱敏工具的范畴啦，而且存储加密数据会侵入业务

**Comment by mouyong** [comment]
┭┮﹏┭┮，我一直以为这样的是脱敏工具的范畴。可能我理解错了叭
